'''Tiferet Flask assets.'''

# *** exports

# ** app
from .core import (
    APP_FLAG,
    GET_ROUTE_EVT_SERVICE_ID,
    GET_ROUTERS_EVT_SERVICE_ID,
    GET_STATUS_CODE_EVT_SERVICE_ID,
)
from .cors import (
    CORS_ALLOW_HEADERS_CONST_KEY,
    CORS_EXPOSE_HEADERS_CONST_KEY,
    CORS_MAX_AGE_CONST_KEY,
    CORS_METHODS_CONST_KEY,
    CORS_ORIGINS_CONST_KEY,
    CORS_SUPPORTS_CREDENTIALS_CONST_KEY,
    parse_cors_options,
)
from .swagger import (
    DEFAULT_API_DESCRIPTION,
    DEFAULT_API_TITLE,
    DEFAULT_API_VERSION,
    SWAGGER_BLUEPRINT_NAME,
    SWAGGER_OPENAPI_JSON_PATH,
    SWAGGER_STATIC_FOLDER,
    SWAGGER_STATIC_URL_PATH,
    SWAGGER_UI_BUNDLE_JS_FILENAME,
    SWAGGER_UI_CSS_FILENAME,
    SWAGGER_URL_PREFIX,
    build_swagger_ui_html,
)
from . import swagger
